# Generated by Django 5.0.4 on 2024-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_instrumento_instrumentoaire_instrumentoviento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentoaire',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='instrumentoviento',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='instrumentoaire',
            field=models.ManyToManyField(to='producto.instrumentoaire'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='instrumentoviento',
            field=models.ManyToManyField(to='producto.instrumentoviento'),
        ),
    ]
