# Generated by Django 5.0.4 on 2024-05-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_remove_instrumentoaire_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentoViento',
            new_name='Instrumentocuerdas',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='instrumentoviento',
            new_name='instrumentocuerdas',
        ),
    ]
